#!/usr/bin/env ruby
#
# this script is the stub command for testing
#
require 'slop'
require 'shellwords'
require 'digest'

options = Slop.parse do
  on 's=', 'sleep=', 'sleep command', as: Numeric
  on 'p', 'progress', 'output progress banner to stdout'
  on 'f', 'fail', 'fail to exit'
end.to_hash

def exit_with_option(result, force)
  exit(1) if force
  exit(result)
end

path = Shellwords.escape(ARGV.last)
if path !~ /^-/ && options.to_hash.empty?
  `touch #{path}`
end

if options[:sleep]
  id = Digest::MD5.hexdigest(rand(10000).to_s)[0..5]
  time = options[:sleep].to_f
  while time > 0
    STDOUT.write(sprintf("@OUT[%s] %f - %s\n", id, time, Time.now)) if options[:progress]
    STDERR.write(sprintf("@ERR[%s] %f - %s\n", id, time, Time.now)) if options[:progress]
    STDOUT.flush
    STDERR.flush
    time -= 0.1
    sleep(0.1)
  end
end

exit_with_option(0, options[:fail])
